modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory (24 is current forge version)

license="All rights reserved"

[[mods]] #mandatory
modId="eanimod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Genetic Animals" #mandatory
description='''
Genetics with improved animal behaviour and extra animal content.
'''